### ISSUE TITLE
@type/PrismJS is not a module error.

### ISSUE THREAD

**Issue by dispensable** [dimpu/angular2-markdown#1]
Hi, I am trying to use this directive module in my little project, but when I import and compile with angular-cli, it shows:
ERROR in [default] node_modules/angular2-markdown/src/app/markdown/markdown.directive.ts:5:23 
File 'node_modules/@types/PrismJS/index.d.ts' is not a module.

I have tried to make prism type be a module with:
export = Prism;

It can be compiled, BUT it can't work either. 

In the console:
Uncaught Error: Unexpected value 'MarkdownModule' imported by the module 'PublishModule'

Any advice for solving this problem will be appreciated.

**Comment by dispensable** [comment]
I just solved it by copying markdown.directive.ts and markdown.module.ts from node-module folder to my own folder. Import them as my own module, and it worked.
Seems like the npm's problem?

**Comment by dimitriy-k** [comment]
I have created my own pipe based on https://github.com/conclurer/markdown-to-html-pipe, which has also bugs and will not work if you install it from github

pipe is more elegant way to transform markdown

**Comment by dimpu** [comment]
This issue is with Prismjs Typings. It's supposed to export PrismJs as typescript module.

in your /node_modules/@types/prismjs/index.d.ts
at the end add.

```ts
export module PrismJs {

}
```

or another way is to use `require` instead of import in `markdown.directive.ts`. 


I'm rewriting this component with all these bug fixes and some more new features. I will release it in two days.

**Comment by dimpu** [comment]
I have fixed all issue

now you can install 
```shell
npm i angular2-markdown@1.3.0 
```

**Comment by dispensable** [comment]
I don't know why but:

ERROR in [default]node_modules/angular2-markdown/src/app/markdown/markdown.component.ts:39:13 
Cannot find name 'Prism'.

ERROR in [default] /node_modules/angular2-markdown/src/app/markdown/markdown.component.ts:58:13 
Cannot find name 'Prism'.

Already changed @type/prismjs to:

```
export module PrismJs {

}
```
still can not work :(

**Comment by amellnik** [comment]
I'm also having the same problem as @dispensable -- with 

```
`-- angular2-markdown@1.3.2
  +-- @types/marked@0.0.28
  +-- @types/prismjs@1.4.18
  `-- prismjs@1.5.1
```

and angular 2.1.1 I get the `Cannot find name 'Prisim'.` error.

**Comment by dispensable** [comment]
@amellnik @dimpu has solved this. 

> in your /node_modules/@types/prismjs/index.d.ts
> at the end add.
> 
> export module PrismJs {
> 
> }
