### ISSUE TITLE
Implicit any type when use noImplicitAny typescript config flag

### ISSUE THREAD

**Issue by ppenalver** [dimpu/angular2-markdown#11]
ERROR in [default] ../node_modules/angular2-markdown/src/app/markdown/markdown.component.ts:90:40 
Parameter 'line' implicitly has an 'any' type.

ERROR in [default] ../node_modules/angular2-markdown/src/app/markdown/markdown.service.ts:10:13 
Parameter 'path' implicitly has an 'any' type.

**Comment by dimpu** [comment]
PR Done!!!

**Comment by ppenalver** [comment]
Thank you!!!
