### ISSUE TITLE
Failing ng build --prod due to empty metadata in prism.languages.metadata.json

### ISSUE THREAD

**Issue by jornare** [dimpu/angular2-markdown#110]
Using Angular 5.1 and @angular/cli@1.6.0 the build fails with an error
"ERROR in TypeError: Cannot read property 'version' of null"

I have traced this down to node-modules/angular2-markdown/markdown/prism.languages.metadata.json
This file should contain module metadata, but only contains [null].

This causes the @angular/compiler build to fail (compiler.umd.js line 29610) where the compiler expects metadata.

I'm using angular2-markdown@2.2.0 and it has downloaded prismjs@1.9.0 and marked@0.3.7

**Comment by tevenFr** [comment]
Same issue here with build --prod :  ERROR in TypeError: Cannot read property 'version' of null

**Comment by tevenFr** [comment]
for the moment, just replace [null] by [] in ../node_modules/angular2-markdown/markdown/prism.languages.metadata.json

**Comment by Metsuryu** [comment]
I'm having the same problem.

For now I'm just using the older 1.6.0 version which seems to work fine.

**Comment by jornare** [comment]
Why did this get closed @dimpu ? Where is the fix?

**Comment by Metsuryu** [comment]
@jornare It's fixed in the version 2.2.2
