### ISSUE TITLE
Cannot build using AOT

### ISSUE THREAD

**Issue by blackholegalaxy** [dimpu/angular2-markdown#17]
By building Angular2 app worked perfectly until I installed angular2-markdown.

Here is the error at compilation time:

> ERROR in Error encountered resolving symbol values statically. Calling function 'makeParamDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in node_modules/angular2-markdown/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in node_modules/angular2-markdown/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in node_modules/angular2-markdown/node_modules/@angular/core/src/di/opaque_token.d.ts
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'src'
>  @ ./src/main.ts 5:0-74
>  @ multi main
> 
> ERROR in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
> Module not found: Error: Can't resolve 'src\$$_gendir' in 'node_modules\@angular\core\src\linker'
>  @ ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js 71:15-36 87:15-102
>  @ ./~/@angular/core/src/linker.js
>  @ ./~/@angular/core/src/core.js
>  @ ./~/@angular/core/index.js
>  @ ./src/main.ts
>  @ multi main

Removing the angular2-markdown module solves the problem but I need it.

**Comment by jfcere** [comment]
Try to pull on the master branch as #14 solved this problem but it is not currently released on npm.

Please give us a feedback if it solved your issue.

**Comment by blackholegalaxy** [comment]
Merci en effet ça a pu résoudre le problème. Un bonjour de Québec ;)

**Comment by blackholegalaxy** [comment]
Ok I tried to build with master as version to use in package.json. I first thought it was doing the job but it was because my colleague actually removed the module form imports (to wait until the module is fixed).

app.module.ts contains:
`MarkdownModule.forRoot(),`

and I encounter the same error as stated in the first post.

I tried to remove and rebuild npm dependencies with no success.

**Comment by jfcere** [comment]
Sorry about that, seems #14 solved the problem for JiT but not for AoT, ill try it and come back to you shortly.

**Comment by jfcere** [comment]
After lots of search through Github issues I found that the problem with AoT would be related to Angular-CLI not being able to resolve node modules inside other node modules.

However, following some workaround, I've been able to compile an application with AoT using angular2-markdown by doing the some modifications to `tsconfig.json`:

- Add relative paths to node_modules for angular dependencies
- Exclude `test.ts` file (loading TestBed pull on dependencies that are not needed when serving app)

Also I had to make a small fix in `markdown.component` and the pull request #19 (which include the fix) is waiting for approval.

You can either wait for the pull request to be approved or try it by pulling directly on the branch to see if it works for you.

Here is the `tsconfig.json` configuration that i used
```diff
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "paths": {
+      "@angular/common": ["../node_modules/@angular/common"],
+      "@angular/compiler": ["../node_modules/@angular/compiler"],
+      "@angular/core": ["../node_modules/@angular/core"],
+      "@angular/forms": ["../node_modules/@angular/forms"],
+      "@angular/http": ["../node_modules/@angular/http"],
+      "@angular/platform-browser": ["../node_modules/@angular/platform-browser"],
+      "@angular/platform-browser-dynamic": ["../node_modules/@angular/platform-browser-dynamic"],
+      "@angular/router": ["../node_modules/@angular/router"],
+      "rxjs/Rx": ["../node_modules/rxjs/Rx"],
+      "rxjs/add/operator/toPromise": ["../node_modules/rxjs/add/operator/toPromise"]
    }
  },
  "exclude": [
+    "test.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit" : true
 }
}
```

**Comment by blackholegalaxy** [comment]
Did you removed your branch where you fixed the problem?

**Comment by jfcere** [comment]
Yes, althought this is a great third party it takes too long for pull requests to be merged and released on npm so I switched to another package.

The solution is in my previous post if you want to submit the changes.

**Comment by dimpu** [comment]
please upgrade it to 1.3.7
