### ISSUE TITLE
problems with < or >

### ISSUE THREAD

**Issue by OG84** [dimpu/angular2-markdown#23]
hi, has anybody experienced problems when the markdown contains a code block with  < or > ?

i get the following result:

![image](https://cloud.githubusercontent.com/assets/5689965/22626059/e3275a90-eba4-11e6-90f0-f96a9908fba4.png)

I'm using your awesome directive like this:

![image](https://cloud.githubusercontent.com/assets/5689965/22626064/18038fe0-eba5-11e6-8eaf-72e5eff4bd50.png)

where ```blogPost.text``` is a markdown string. Here the < and > are still ok.

**Comment by dimpu** [comment]
Can you post your "blogPost.text" file

**Comment by dimpu** [comment]
when you use [innerHTML] it will automatically do the safe conversion so you can't do like this. instead, you can add external path.

<markdown path="/path/to/code.cpp"></markdown>

I will try to add provide a much better way to do this in my next release. Thanks.
