### ISSUE TITLE
Cannot find module 'angular2-markdown'

### ISSUE THREAD

**Issue by ryanpflem** [dimpu/angular2-markdown#28]
When importing in app.module.ts as `import { MarkdownModule } from 'angular2-markdown';` 
console error is: `Cannot find module 'angular2-markdown'`

When import statement is changed to  `import { MarkdownModule } from 'angular2-markdown/bundles';`
`Cannot find module 'angular2-markdown'` error goes away.

When import statement is `import { MarkdownModule } from 'angular2-markdown/bundles';`
and `@NgModule` import is `MarkdownModule.forRoot()`

new console error is `Can't resolve all parameters for MarkdownService: (?).`

originalStack:
`"Error: Can't resolve all parameters for MarkdownService: (?).
    at SyntaxError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:147841:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:103421:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:11245:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:4200/vendor.bundle.js:25641:31)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:4200/vendor.bundle.js:25516:26)
    at CompileMetadataResolver._getInjectableMetadata (http://localhost:4200/vendor.bundle.js:25504:21)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:4200/vendor.bundle.js:25746:40)
    at http://localhost:4200/vendor.bundle.js:25704:49
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (http://localhost:4200/vendor.bundle.js:25671:19)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:25355:50)
    at CompileMetadataResolver.getNgModuleSummary (http://localhost:4200/vendor.bundle.js:25211:52)
    at http://localhost:4200/vendor.bundle.js:25282:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:25269:49)"`

Any thoughts on how to get module working?

Current dependencies:

```
+-- @angular/cli@1.0.0-beta.31
+-- @angular/common@2.4.7
+-- @angular/compiler@2.4.7
+-- @angular/compiler-cli@2.4.7
+-- @angular/core@2.4.7
+-- @angular/forms@2.4.7
+-- @angular/http@2.4.7
+-- @angular/platform-browser@2.4.7
+-- @angular/platform-browser-dynamic@2.4.7
+-- @angular/router@3.4.7
+-- @types/jasmine@2.5.38
+-- @types/node@6.0.63
+-- angular2-markdown@1.3.6
+-- bootstrap@4.0.0-alpha.6
+-- codelyzer@2.0.0
+-- contentful@3.8.1
+-- core-js@2.4.1
+-- font-awesome@4.7.0
+-- jasmine-core@2.5.2
+-- jasmine-spec-reporter@2.5.0
+-- karma@1.2.0
+-- karma-chrome-launcher@2.0.0
+-- karma-cli@1.0.1
+-- karma-jasmine@1.1.0
+-- karma-remap-istanbul@0.2.2
+-- ng2-bootstrap@1.3.3
+-- protractor@4.0.14
+-- rxjs@5.1.1
+-- simple-line-icons@2.4.1
+-- ts-helpers@1.1.2
+-- ts-node@1.2.1
+-- tslint@4.4.2
+-- typescript@2.0.10
`-- zone.js@0.7.7
```

**Comment by railto** [comment]
Having the same issue, have had to revert back to 1.3.5 for now

**Comment by dimpu** [comment]
Sorry I didn't test it. I will push new update to night mean while use 1.3.5. Im trying to provide solution for all build systems.

**Comment by dimpu** [comment]
Now, this issue got resolved. Pease upgrade to 1.3.7 version. @ryanpflem . please close this thread if it's working for you. Thanks.

**Comment by railto** [comment]
Still having same issue, tried 1.3.7 and 1.3.8 which is current default

**Comment by dimpu** [comment]
I have created a new project using ng cli. Its working fine for me. How are u doing this.

**Comment by railto** [comment]
Ah, think im on an old version of ng cli, gonna rebuild in latest version later

**Comment by dimpu** [comment]
Cool! I will keep this thread open. Close it after you are done. Thanks:)

**Comment by railto** [comment]
I've tested this on a fresh install with the most up to date version of @angular/cli and am still getting this issue.

**Comment by ryanpflem** [comment]
I just tried to import with v.1.3.8 and am still getting the same error.  
I'm using `@angular/cli: 1.0.0-beta.31`

**Comment by DinkuMM** [comment]
Me too getting the same issue.
i have install it using the 'npm i angular2-markdown --save' command.
When importing in app.module.ts as import { MarkdownModule } from 'angular2-markdown';
console error is: Cannot find module 'angular2-markdown'

**Comment by dimpu** [comment]
I rewrote the complete build system. Please check new readme doc. @ https://github.com/dimpu/angular2-markdown
