### ISSUE TITLE
Unexpected value 'MarkdownModule' imported by the module 'ShellModule'

### ISSUE THREAD

**Issue by zpydee** [dimpu/angular2-markdown#3]
Following your instructions, I get the above error when running my project. Given this is the first 3rd party angular 2 library I'm using, I'm sure the issue is related to a lack of understanding on my part, but any guidance would be highly appreciated.

Thanks in advance!

**Comment by dimpu** [comment]
I'm not sure why you getting that issue. 

Try importing component instead of the module and put that in in your declarations.

```ts
import {MarkdownComponent} from 'angular2-markdown';

@NgModule({
  declarations: [MarkdownComponent]
})
export class MyModule { }
```
