### ISSUE TITLE
Quote is not rendered

### ISSUE THREAD

**Issue by ArtworkAD** [dimpu/angular2-markdown#33]
See https://dimpu.github.io/angular2-markdown/

Quote is not rendered at all

**Comment by dimpu** [comment]
Could  you please tell me what is your input and expected output?

**Comment by ArtworkAD** [comment]
@dimpu 

Input:

```
> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.
```

Output:

```
> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.
```

Expected output:

> Blockquotes are very handy in email to emulate reply text.
> This line is part of the same quote.

**Comment by dimpu** [comment]
I don't see any issue with that. It's working fine.

This is live demo link. I just copy pasted above test. It's working fine for me.

https://dimpu.github.io/angular2-markdown/varibale



[demo]: http://i.hmp.me/m/3ff44568f099f2aab82ab8ff201067eb.png ""

**Comment by dimpu** [comment]
Please let me know if it's working

**Comment by michal-kindl** [comment]
By my tests the Blockquotes were rendered correctly when using 
`<markdown [data]="some.data"></markdown>` 
form, otherwise not...

**Comment by dimpu** [comment]
Could you please upload a plunker demo so that I can help you better.
