### ISSUE TITLE
Nested list not displaying correctly

### ISSUE THREAD

**Issue by nombrekeff** [dimpu/angular2-markdown#35]
Nested md list not nesting html correctly

```
* Parent li
  * Child li
```

This example should become:
```html
<li>
  Parent li
  <ul>
    <li>Child li</li>
  </ul>
</li>
```
But instead it becomes
```html
<ul>
  <li>
    Parent li
  </li>
<ul>
<ul>
  <li>Child li</li>
</ul>
```

**Comment by dimpu** [comment]
It's a bug with [marked](https://github.com/chjj/marked/issues/258) library. We don't have any fix for this yet.

**Comment by nombrekeff** [comment]
Okey thanks i will check in some time to see if its fixed
