### ISSUE TITLE
Formatting of text not as desired

### ISSUE THREAD

**Issue by guehmann** [dimpu/angular2-markdown#36]
Hi,

i like this project. Tried to use it with Angular and Material2 Beta. I'd like to show the markup in an MdDialog in the content area.

This is the preview from my Visual Studio Markup Addin:
![image](https://cloud.githubusercontent.com/assets/8971747/23713245/9684fa50-0425-11e7-8ba3-9de4ead74353.png)

This is the result in the application:
![image](https://cloud.githubusercontent.com/assets/8971747/23713277/b2ddba52-0425-11e7-8a38-2ebec4b68598.png)

Someone any idea what i'm doing wrong. The 'mat-dialog-content' style has only set the margins set.

Many thanks in advance.
Regards Jens.

**Comment by dimpu** [comment]
Is it possible to reproduce in a plunker plz?

**Comment by guehmann** [comment]
Thanks for reply, At the moment it's a large project, I'll try it to produce it in a plunkr. Thank you.

**Comment by guehmann** [comment]
Sorry for my late reply. While trying to prepare the plunker I a a style in one of my stylesheets was responsible for the behaviour. Now the output is as desired.
Thank you and sorry for inconveniences.

Regards Jens
