### ISSUE TITLE
Dynamically modifying text causes prism to break

### ISSUE THREAD

**Issue by itskibo** [dimpu/angular2-markdown#37]
[Plunkr](https://plnkr.co/edit/2I4xtJ3VhOViUM0tRyOh?p=preview)

Before
![Before modifying text](https://i.gyazo.com/59f8351e846db5ec4a9c03eb360b7a53.png)

After
![After modifying text](https://i.gyazo.com/1ae0da1d680d5774caf277fd3624dee1.png)

The only "fix" I have found so far is by changing routes or reloading the page. Not entirely sure what is causing it, but I feel like it has to do with it not executing prism correctly.

**Comment by dimpu** [comment]
Issue fixed. You can check the same in your [plunker](https://plnkr.co/edit/2I4xtJ3VhOViUM0tRyOh?p=preview).
