### ISSUE TITLE
sub-list is not working.

### ISSUE THREAD

**Issue by davidkang200** [dimpu/angular2-markdown#38]
https://dimpu.github.io/angular2-markdown/

## markdown

<img width="449" alt="screen shot 2017-03-13 at 11 43 25 pm" src="https://cloud.githubusercontent.com/assets/18748215/23859430/e6df430a-0846-11e7-862f-60890ec17b8f.png">

## html

<img width="512" alt="screen shot 2017-03-13 at 11 43 34 pm" src="https://cloud.githubusercontent.com/assets/18748215/23859434/e8668e54-0846-11e7-9e39-3cf107198680.png">

**Comment by dimpu** [comment]
#35

**Comment by chauey** [comment]
it still does not seem to work for me. it puts them all at the same level

**Comment by dimpu** [comment]
Sub list not working yet. The issue is with marked library. We don't have My fix for this right now. Waiting for next update from marked library. If I don't get one soon.
