### ISSUE TITLE
Cannot find name 'Prism'

### ISSUE THREAD

**Issue by hoantp** [dimpu/angular2-markdown#4]
I'm using Angular2 CLI (https://cli.angular.io) to create a new project. But when using this lib and run `ng serve`, it throwed:

`.../node_modules/angular2-markdown/src/app/markdown/markdown.component.ts:65:13
Cannot find name 'Prism'.`

The Markdown still works but maybe it can not highlight the code.

**Comment by janklan** [comment]
Same here.

**Comment by truongnguyen** [comment]
in tsconfig.json, add the following line:

declare var Prism: any;

**Comment by ivanvladimir** [comment]
I'm getting the same error, the previous solution does not work

`.../node_modules/angular2-markdown/src/app/markdown/markdown.component.ts (53,14): Cannot find name 'Prism'.`

**Comment by truongnguyen** [comment]
Correction: in typings.d.ts file
add `declare var Prism: any;`
