### ISSUE TITLE
Fetching remote resources twice

### ISSUE THREAD

**Issue by midzer** [dimpu/angular2-markdown#46]
Hi. Looking into network tab of Chromium development console, it appears remote markdown files are fetched twice:

![Remote resources fetching twice](https://abload.de/img/selection_001mrsaw.png)

It was included single time via `<markdown [path]="'assets/markdown/index.md'"></markdown>`.
Using line `<div Markdown [path]="'assets/markdown/index.md'"></div>` had same effect.

Is it an issue in `zone.js`?

Cheers,
midzer

**Comment by dimpu** [comment]
It's difficult to tell. Could you please create plunker.  You can use the existing plnker https://plnkr.co/edit/haatIMLjfA0VbGeN4lGm?p=preview
and create your own version out of it. 

For me, I don't see any such issue on my machine.

**Comment by dimpu** [comment]
@midzer your are right. it's issue with zone.js. Change your zone.js version to 0.8.5.

**Comment by midzer** [comment]
Thanks for your advice, but I think sticking to a fixed version is not viable option in the long term.
In development mode zone.js 0.8.5 doesn't fetch the whole file second time but still a fraction of it (probably cached version).
The issue still exists in production as markdown files are XHR fetched twice, as you can see in my preview here http://rohner.io/preview/
