### ISSUE TITLE
Ability to extend Renderer

### ISSUE THREAD

**Issue by paullryan** [dimpu/angular2-markdown#49]
Given that your using marked.js and it's designed to be extended it would be beneficial to have direct access to the renderer (via the service). So maybe export the service and give an accessor to the direct renderer so users can extend the rendering functionality (for example I need to have more control over image rendering which I can do in marked via the renderer by extending the image syntax).

**Comment by dimpu** [comment]
It's already on the todo list. But I'm really busy right now. It would be greate if someone can send a PR.

**Comment by paullryan** [comment]
Are you ok with the design I mention above (exposing the renderer through a getter and exposing the service to the module)? If you say yes I'll do a quick PR.

**Comment by dimpu** [comment]
Sure. Even I want it. But make sure. It' won't break anything. 

Thanks a lot.

**Comment by paullryan** [comment]
@dimpu ok PR is ready.

**Comment by dimpu** [comment]
Thanks a lot @paullryan. Merged your PR.

**Comment by paullryan** [comment]
@dimpu thanks, you should also re-publish the demo page as there are some new examples in there.

**Comment by dimpu** [comment]
Yes. I will do that.
