### ISSUE TITLE
MarkdownComponent.prepare removes indention

### ISSUE THREAD

**Issue by dhcode** [dimpu/angular2-markdown#52]
I have a markdown file that uses sometimes 4 whitespaces to indent code blocks.
When I feed this directly to marked, I get the desired results. But with the `MarkdownComponent` of this project, the code blocks are not rendered. After debugging through the code, I found the [`prepare`](https://github.com/dimpu/angular2-markdown/blob/master/src/markdown/markdown.component.ts#L93) method which removes the whitespaces and with it the whole intentional formatting.

In the closed issues, there seem to be several issues that are probably related, but it was always pointed to marked, when in fact the `prepare` method is the cause.
Examples: #47, #41, #38 , #36 , #35 

Suggestion: Just `return raw` instead of modifying the text.

**Comment by dimpu** [comment]
Please upgrade to latest version 1.6.0. It fixes all issues you mentioned.

**Comment by cre8** [comment]
When I load the code directly in markdown from a variable it is still without white-spaces. But when I edit it (when it's synced with a textarea) it will be formatted the right way.

**Comment by dhcode** [comment]
It does not work for me with v1.6.0 either, if I want to display a markdown file like this:

`<markdown path="assets/docs.md"></markdown>`

The MarkdownComponent prepare function still removes the indentions.

**Comment by ogu-level-it** [comment]
This problem is visible on the demo : [https://dimpu.github.io/angular2-markdown/](https://dimpu.github.io/angular2-markdown/)

**Comment by bob-lee** [comment]
Umm, code block starting line seems to be sensitive to leading spaces. That's so even in this Github site. In first block below, I started html block with 4 leading spaces, then 3 backticks and *html*. The result looks not ok. Workaround was removing all leading spaces in starting line (second block). 

    ```html
    <div>Hi</div>
    ```
```html
    <div>Hi</div>
```
Other than that, indenting in codes itself seems to be preserved well using this library. As always, providing clear instructions on how to reproduce issue should help.
