### ISSUE TITLE
Cache remote fetched resources

### ISSUE THREAD

**Issue by midzer** [dimpu/angular2-markdown#53]
Good morning,
is there a way to prefetch remote markdown files i.e. on application startup and cache them to display later without another GET?
In my app main loading time is no big issue and i want to show those resources as fast as possible.

Cheers,
midzer

**Comment by dimpu** [comment]
I think you can do it in within you application.

**Comment by paullryan** [comment]
@midzer as Dimpu says you'll want to do this in your app logic and use the `[data]` binding for the content passed to the markdown directive.
