### ISSUE TITLE
Using Mathjax with Markdown

### ISSUE THREAD

**Issue by PrithiviRajG** [dimpu/angular2-markdown#54]
We want to use formula inside the markdown.. is it possible to add mathjax with this plugin which can render formulas too?

Thanks

**Comment by paullryan** [comment]
@PrithiviRajG You'd want to use the new access to the marked object (see https://github.com/dimpu/angular2-markdown#marked-customization) to get the lexer. Then write a custom marked lexer rule for `/\$\$(.*)?\$\$/` (see https://github.com/chjj/marked#access-to-lexer-and-parser) and pass that to the MathJax library in a custom renderer callback function.
