### ISSUE TITLE
Custom css for markdown

### ISSUE THREAD

**Issue by midzer** [dimpu/angular2-markdown#56]
Hi again,
i want to style my markdown files in a custom way.

For code syntax i would prefer any `prism.css` for sure. In my case i want to treat some `<a>` in a special way.

How do i achieve that?
Including an own `markdownstyle.css` globally with
```
a {
  text-decoration: none;
}
```
for example would override any `<a>` in my whole app.

Thanks for your support and have a friendly weekend,
midzer

**Comment by paullryan** [comment]
The best way at the moment is to have all styles as children of markdown

e.g.
```css
markdown a {
  text-decoration: none;
}
```

**Comment by midzer** [comment]
Thanks for your answer @paullryan. This is working perfectly.
