### ISSUE TITLE
could u tell me the difference between Source Demo and Online Demo

### ISSUE THREAD

**Issue by Ryfthink** [dimpu/angular2-markdown#57]
**Source Demo**
![image](https://cloud.githubusercontent.com/assets/3376909/25991207/11ea9870-3735-11e7-8057-f846dcfc44f8.png)

***

**Online Demo**
![image](https://cloud.githubusercontent.com/assets/3376909/25991238/2dfc5170-3735-11e7-83b9-4f452fece14b.png)

**Comment by dimpu** [comment]
No difference both same.
