### ISSUE TITLE
Implicit type any throws errors when using webpack

### ISSUE THREAD

**Issue by xgebi** [dimpu/angular2-markdown#6]
I am using Angular 2.2.3 and I am building the whole thing with webpack. When I try to build I get 

ERROR in C:\...\node_modules\angular2-markdown\src\app\markdown\markdown.service.ts
(9,14): error TS7006: Parameter 'path' implicitly has an 'any' type.

ERROR in C:\...\node_modules\angular2-markdown\src\app\markdown\markdown.component.ts
(84,41): error TS7006: Parameter 'line' implicitly has an 'any' type.

I tried setting both parameters to _any_ and to _string_, unfortunately neither worked for me.

**Comment by Clepto** [comment]
Hello, 

I had the some problem as you did but changing the parameters to :string fixed it for me.
Maybe you can try changing "noImplicitAny" to false in your tsconfig.json.

**Comment by xgebi** [comment]
Hi @Clepto changing parameters in my local copy isn't clean at all. Better but still bad solution is to use suppressImplicitAnyIndexErrors: true especially when you are working on a project in a team. noImplicitAny helps preventing errors in code.
