### ISSUE TITLE
The markdown tag shows the index.html file when loading from server

### ISSUE THREAD

**Issue by BalamChaac** [dimpu/angular2-markdown#61]
<markdown [path]="publicationHead.publicationUrl"></markdown>

The tags should show nothing while the website is loading

this is the live example
http://naktan.yakanda.mx/blog/publications/BgMPAQUIAQw

I do not know why, but while it loads it shows the index of the website.

**Comment by dimpu** [comment]
@BalamChaac What exactly you trying to do here?
