### ISSUE TITLE
marked is not a function

### ISSUE THREAD

**Issue by LoloSh** [dimpu/angular2-markdown#63]
I'm trying to create a markdown editor in my angular2 project  with this package and I have this important issue :   " marked "     is not a function . The error comes from those lines : 

  // comple markdown to html
  public compile(data: string) {
    return marked(data);
  }

Do you have any idea what can I do to fix the issue ? 

That's the way I create my markdown input in my component : 

<textarea [(ngModel)]="textData" [ngModelOptions]="{standalone: true}"></textarea>
            <markdown [data]="textData"></markdown>

**Comment by dimpu** [comment]
@LoloSh Could you please take a screenshot of your console and post it here.
