### ISSUE TITLE
empty line is removed

### ISSUE THREAD

**Issue by johnking** [dimpu/angular2-markdown#65]
Hi there, 

  Why all the empty lines in the source `.md` file are not rendered in the result page?  

  I also checked the demo of this repository, it has the same `issue`.

  Are there any reasons behind it? And how to resolve it if I need the empty lines? 

thanks

-John

**Comment by Eraldo** [comment]
I think that is the default markdown behaviour.
I have the same issue.

Turning `gfm` for the renderer should solve the problem.

However, I have not yet figured out how to customise the renderer for my whole project.
I do see that they have an example for how to do it for a single component. I want it for my project in general.

**Comment by Eraldo** [comment]
Why was this closed?
Has it been solved?
