### ISSUE TITLE
Using angular2-markdown insinde node_modules folder

### ISSUE THREAD

**Issue by cleptomaniac361** [dimpu/angular2-markdown#68]
I want to use the markdown module inside my node_modules folder to parse some README.md files in some reusable components inside an external module. I tried to import the `MarkdownModule` with `import {MarkdownModule} from "angular2-markdown";` inside my external.module.ts file in the node_modules folder. I also added the `MarkdownModule.forRoot()` to  my imports inside the `@NgModule` decorator. When I use `<markdown> ##Example## </markdown>` inside an HTML file in my module, i receive the following error: 
```
Unhandled Promise rejection: Template parse errors:
'markdown' is not a known element:
1. If 'markdown' is an Angular component, then verify that it is part of this module.
2. If 'markdown' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
```

Pointing to my <markdown> Tag

Is it possible to use the markdown module inside the node_modules folder or do I have to find another way to parse my README.md files?

**Comment by dimpu** [comment]
@cleptomaniac361 Mode does not register properly.

**Comment by Axure** [comment]
In my case, I mis-imported the component into the "routing module", instead of the module. Hope this helps.
