### ISSUE TITLE
[universal] Prism.highlightAll references `document`

### ISSUE THREAD

**Issue by hermagrini** [dimpu/angular2-markdown#69]
`MarkdownComponent` is currently making 3 calls to `Prism.highlightAll`:
- [onDataChange](https://github.com/dimpu/angular2-markdown/blob/master/src/markdown/markdown.component.ts#L52)
- [processRaw](https://github.com/dimpu/angular2-markdown/blob/master/src/markdown/markdown.component.ts#L69)
- [onPathChange](https://github.com/dimpu/angular2-markdown/blob/master/src/markdown/markdown.component.ts#L81)

This causes an error during server compilation, as `document` doesn't exist:
```
ERROR ReferenceError: document is not defined
    at Object.highlightAll
```

A possible solution is to only run that method when in browser using `isPlatformBrowser` from `@angular/common` since, save for when the user has javascript disabled, Angular will take over on the client-side an re-render the component thus calling `highlightAll`.

I'm more than happy to add a PR for this or discuss other possible solutions.

Thanks!

**Comment by dimpu** [comment]
@hermagrini This project doesn't support server side rendering yet. But we will try it on next release.
