### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by Clepto** [dimpu/angular2-markdown#7]
Hello, 

I followed the instructions in the README but I get this error in the browser:

`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/angular2-markdown`

I mapped
`'angular2-markdown':         'node_modules/:angular2-markdown/index.ts',`

in my systemjs.config.js but then I get another error 

`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-markdown/src/app/markdown/markdown.module`

I tried adding the relevant map to systemjs.config.ts but it didn't work.

Thanks

**Comment by dimpu** [comment]
Change map 'angular2-markdown': 'node_modules/:angular2-markdown/index.ts' to

'angular2-markdown': 'node_modules/angular2-markdown'
