### ISSUE TITLE
Get error after adding

### ISSUE THREAD

**Issue by CordlessWool** [dimpu/angular2-markdown#70]
I install the model via npm and added it to app.module.ts. But after this my hole up crashed. After removing it from imports in app.module everything runs fine again. Do I miss something or is it an error inside angular2-markdown? Without the markdown lib everything runs without an error message.

`Error: (SystemJS) expected expression, got '<'
	@http://localhost:3000/app/app.module.js:15:27
	@http://localhost:3000/app/app.module.js:1:31
	@http://localhost:3000/app/app.module.js:1:2
	@http://localhost:3000/app/main.js:7:20
	@http://localhost:3000/app/main.js:1:31
	@http://localhost:3000/app/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:391:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:141:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:831:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:424:17
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:191:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:595:25
	ZoneTask.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:502:21
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:1364:9
	globalZoneAwareCallback@http://localhost:3000/node_modules/zone.js/dist/zone.js:1382:17
	
	Evaluating http://localhost:3000/angular2-markdown
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
Stack trace:
(SystemJS) expected expression, got '<'
	@http://localhost:3000/app/app.module.js:15:27
	@http://localhost:3000/app/app.module.js:1:31
	@http://localhost:3000/app/app.module.js:1:2
	@http://localhost:3000/app/main.js:7:20
	@http://localhost:3000/app/main.js:1:31
	@http://localhost:3000/app/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:391:17
	Zone.prototype.run@http://localhost:3000/node_modules/zone.js/dist/zone.js:141:24
	scheduleResolveOrReject/<@http://localhost:3000/node_modules/zone.js/dist/zone.js:831:52
	ZoneDelegate.prototype.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:424:17
	Zone.prototype.runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:191:28
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:595:25
	ZoneTask.invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:502:21
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:1364:9
	globalZoneAwareCallback@http://localhost:3000/node_modules/zone.js/dist/zone.js:1382:17
	
	Evaluating http://localhost:3000/angular2-markdown
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js`

**Comment by midzer** [comment]
Hi.
`Error: (SystemJS) expected expression, got '<'` looks like a syntax error to me.

This is how i imported this library in my project:
`import { MarkdownModule } from 'angular2-markdown';` followed by
`imports: [
    MarkdownModule.forRoot()
]`

**Comment by dimpu** [comment]
@CordlessWool I think @midzer  is correct.
