### ISSUE TITLE
code syntax highlight for javascript arrow function '=>'

### ISSUE THREAD

**Issue by bob-lee** [dimpu/angular2-markdown#73]
First, thanks for great library. I got markdown for javascript code below:
>setTimeout(_ => this.inside = groupName ? true : false);

I expected it is shown like
```javascript
setTimeout(_ => this.inside = groupName ? true : false);
```
But actually (arrow part broken)
```javascript
setTimeout(_ =&gt; this.inside = groupName ? true : false);
```

**Comment by bob-lee** [comment]
I was using it like:
```html
        <markdown>
          {{note.text}}
        </markdown>
```
and ng-content seems to be sanitized.. Changing as below fixed the problem:
```html
        <markdown [data]="note.text"></markdown>
```
Not sure there is a room to improve but `[data]` binding should be a preferred way. See [this demo](https://plnkr.co/edit/VjUlWdSRjs1vWiE8PACW).

**Comment by dimpu** [comment]
@bob-lee Thanks.
