### ISSUE TITLE
Code block running markdown rules inside it

### ISSUE THREAD

**Issue by PedroEsperanca** [dimpu/angular2-markdown#74]
The following markdown code:
```
{ path: '**',   redirectTo: '', pathMatch: 'full' }
```

Gets rendered like this:
![image](https://user-images.githubusercontent.com/1115163/28963834-7dadaba6-7902-11e7-896b-8611280b8705.png)

This is clearly because `**` is evaluated as Markdown syntax even though it's inside a code block.

**Comment by dimpu** [comment]
@PedroEsperanca I should work fine. I tried your code on online demo. It's good. 
https://dimpu.github.io/angular2-markdown/
