### ISSUE TITLE
'markdown' is not a known element when I use this in childModule

### ISSUE THREAD

**Issue by rxyshww** [dimpu/angular2-markdown#75]
When I use it in rootModule and in ‘’appComponent.html‘’ ,It works properly. But when i use it with chlid route in childmodule, It will prompt ‘'markdown' is not a known element’. 
How can I solve it? Dose it have a method like RouterModule.forChild()?

**Comment by MovGP0** [comment]
just import the declaration into the module: 
```typescript
// ...
import { MarkdownComponent } from "angular2-markdown";

@NgModule({
    declarations: [
        MarkdownComponent, 
        // ...
    ],
    // ...
})
export class MyModule { }

**Comment by yueming-Chen** [comment]
@rxyshww could show off the code of  your main module ?

**Comment by dimpu** [comment]
Closing this issue. Feel free to reopen if didn't fix.
