### ISSUE TITLE
Problems importing marked.js into librarie's MarkdownService injectable

### ISSUE THREAD

**Issue by DSoko2** [dimpu/angular2-markdown#78]
First of all, thanks a lot to everyone helping to provide this great project!

I'm currently facing an issue regarding the import of marked.js into MarkdownService. I'm transpiling my typescript source to es2015 with es2015 modules and try to bundle it using rollup and gulp. The common-js rollup plugin is configured as documented in this project, but I still get the following error, which is breaking my build:

```
../../angular2-markdown/dist/markdown/markdown.service.js (11:36) 'Renderer' is not exported by '../../angular2-markdown/node_modules/marked/lib/marked.js'
../../angular2-markdown/dist/markdown/markdown.service.js (43:15) 'setOptions' is not exported by '../../angular2-markdown/node_modules/marked/lib/marked.js'
Cannot call a namespace ('marked')
```

Actually, I already had a view minutes of debugging and found out that changing https://github.com/dimpu/angular2-markdown/blob/master/src/markdown/markdown.service.ts#L4 from: 
`import * as  marked from 'marked';` to `import marked from 'marked';` solves the issue. So my question to all of you and especially to @dimpu is, whether there is any deeper reason for importing marked this way. I found [another discussion](https://github.com/rollup/rollup/issues/670), which seems to tackle a similar issue and comes up with the same solution as me. The comment of Rhich-Harris there supports that this way of importing may cause compatibility issues with es modules in general.

In case it is not a valid option to change the way the marked.js contents are imported, is there anybody who had a similar issue us es modules and angular2-markdown or has a hint for me?

**Comment by kubica** [comment]
Same problem here

**Comment by DSoko2** [comment]
For everyone facing the same issue: I republished this package on NPM with the fix from my original post above as [@dsoko2/angular2-markdown](https://www.npmjs.com/package/@dsoko2/angular2-markdown). I'm going to keep it up-to-date to this project, until the problem is solved.
