### ISSUE TITLE
Additional toString conversion needed when working with libraries like @ngx-translate

### ISSUE THREAD

**Issue by adrian-the-git** [dimpu/angular2-markdown#84]
I'm currently using `@ngx-translate` to pull language-specific markdown content, and the object produced by that library's pipe is some string-like object I suppose lacks some string methods, so the `marked` library throws a TypeError: "src.replace is not a function." 

I solve this with a simple pipe which calls `toString`: 

`<markdown [data]="'page.content' | translate | string"></markdown>`

This works fine, but it would be great if the string prepare function of `angular2-markdown` performed the conversion automatically.

**Comment by dimpu** [comment]
@adrian-the-git It's a good idea but @jfcere  already created ngx-markdown on npm. @jfcere will be  ok to delete your package from npm so that we can use it for this project. Thanks.
