### ISSUE TITLE
Update to angular 4.4.0-RC.0

### ISSUE THREAD

**Issue by MrHOY** [dimpu/angular2-markdown#86]
When I use angular 4.4. I see they replace angular/http by angular/common/http, so error : Loading http://localhost:3000/node_modules/angular2-markdown/bundles/angular2-markdown.umd.min.js

**Comment by rtm** [comment]
This ought to have been solved in 2.0.0, and probably can be closed now.

**Comment by dimpu** [comment]
@rtm Thanks.
