### ISSUE TITLE
 Secondary list seems not supported.

### ISSUE THREAD

**Issue by kiruto** [dimpu/angular2-markdown#9]
Secondary list like this
- A
  * a1
  * a2
- B
  * b1
  * b2
It's seems not supported.

**Comment by dimpu** [comment]
It seems issue with Marked package. We can't fix it here.

**Comment by kiruto** [comment]
The problem may be you called trim() in file below, at line 90.
https://github.com/dimpu/angular2-markdown/blob/master/src/app/markdown/markdown.component.ts

**Comment by dimpu** [comment]
Probably right but Without trim() the whole functionality break. We may have to find new solution. If u have anything your mind let know here. I'm reponing this issue.

**Comment by dimpu** [comment]
https://github.com/dimpu/angular2-markdown/pull/15

should fix the issue.

**Comment by jfcere** [comment]
Please reopen the issue ... #15 was intended to solve indentation in block code only. This does not affect the bullet list altho the solution would be pretty much the same.

I might take a look at it in a near futur as I am currently using your plugin in a work project and the odds are pretty good that we will need that feature too!
