### ISSUE TITLE
XSS vulnerability of markedjs

### ISSUE THREAD

**Issue by mrkvon** [dimpu/angular2-markdown#91]
`marked` is vulnerable to XSS attacks: [issues here](https://github.com/chjj/marked/issues?utf8=%E2%9C%93&q=is%3Aissue%20xss)

Therefore `angular2-markdown` introduces critical security issues into angular app, when it's used to format user input.

**Comment by dimpu** [comment]
@mrkvon  You can pass
`mangle: true` to the parser. 

```ts
import { MarkdownService } from 'angular2-markdown';
@Component({
    selector='my-comp',
    template: `
    <markdown>
     > Block
     > quote
     > here
    </markdown>
    `,
})
export class MyComp {
  constructor(private _markdown: MarkdownService) {}

  ngOnInit() {
    this._markdown.mangle = true
  }
```
