### ISSUE TITLE
Not all Markdown Formatting is Working

### ISSUE THREAD

**Issue by Programazing** [dimpu/angular2-markdown#92]
I'm using Angular 4.4.4 and Angular CLI  1.4.4.

I followed the directions in your readme for Angular CLI though instead of adding the CSS to ` .angular-cli.json` I added a style link to the CDN CSS. I've also tried using the CSS file in node_module.

The issue is that only some of the markdown formatting seems to be working. 

![markdown](https://user-images.githubusercontent.com/11393826/31138611-18d76d38-a83d-11e7-837f-6c66aa6fdf0f.png)

**Comment by dimpu** [comment]
@Programazing I'm not sure why it's not working for you. But everything works great for me. Check out this example.

https://dimpu.github.io/angular2-markdown/
