### ISSUE TITLE
Security problem!

### ISSUE THREAD

**Issue by xnnkmd** [dimpu/angular2-markdown#94]
The free [nsp ](https://github.com/nodesecurity/nsp) security check tool reports a problem with your package. Thus I am unable to use it. I think you can fix the issues by upgrading the version(s) of your dependencies (some are pretty old):

Here is the output from the tool:

┌───────────────┬───────────────────────────────────────────────────────────────────────────────────────────────┐
│               │ Regular Expression Denial of Service                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Name          │ marked                                                                                        │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ CVSS          │ 7.5 (High)                                                                                    │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Installed     │ 0.3.6                                                                                         │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ All                                                                                           │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Patched       │ None                                                                                          │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ Path          │ .... > angular2-markdown@1.6.0 > marked@0.3.6                                        │
├───────────────┼───────────────────────────────────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/531                                                        │
└───────────────┴───────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by dimpu** [comment]
Problem is not with my project it's `marked@0.3.6`.

**Comment by xnnkmd** [comment]
@dimpu The problem is your project because you are using an insecure package (which is no longer maintained apparently).
