### ISSUE TITLE
Not updating the binded data

### ISSUE THREAD

**Issue by kp-visla** [dimpu/angular2-markdown#95]
I have a code in my template:
`<markdown>{{ text }}</markdown>`
And when the `text` is changed in the model it is not updated in the view.
If I do not put `<markdown>` there then everything works fine. 
Am I doing something wrong or this is just not supported?
Is there any other way to achieve what I want to do using this library?

**Comment by dimpu** [comment]
@kp-visla Maybe I don't understand what you need. But if you looking for using expressions with markdown it should work fine.
https://plnkr.co/edit/haatIMLjfA0VbGeN4lGm?p=preview
update 
`app.model.ts`
```ts
//our root app component
import {Component, NgModule} from '@angular/core'
import { BrowserModule } from '@angular/platform-browser'

// import angular2-markdown module
import { MarkdownModule } from 'angular2-markdown';

@Component({
  selector: 'my-app',
  template: `
    <markdown>
      {{md}}
    </markdown>
  `,
})
export class AppComponent {
  constructor() {
    this.md = `## Marked content`
  }
}

@NgModule({
  imports: [BrowserModule,MarkdownModule.forRoot()],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by kp-visla** [comment]
@dimpu Thank you for the answer. But if the value of the md is changed later (after the view is rendered) would it be updated? It's not working for me.

**Comment by dimpu** [comment]
@kp-visla It's against angular architecture We can't do that instead of that you can do data binding with data attribute. 

```ts
//our root app component
import {Component, NgModule} from '@angular/core'
import { BrowserModule } from '@angular/platform-browser'

// import angular2-markdown module
import { MarkdownModule } from 'angular2-markdown';

@Component({
  selector: 'my-app',
  template: `
    <markdown [data]="this.md">
    
    </markdown>
  `,
})
export class AppComponent {
  constructor() {
    this.md = `## Marked content`;
    
    setTimeout(()=>{
      this.md = `aravind`
    },2000);
    
  }
}

@NgModule({
  imports: [BrowserModule,MarkdownModule.forRoot()],
  declarations: [AppComponent],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
