### ISSUE TITLE
Embed Angular component tag inside Markdown file

### ISSUE THREAD

**Issue by jxm-math** [dimpu/angular2-markdown#96]
I have recently discovered the Angular2 Markdown project and I have found it extremely valuable for a project that I am currently building in Angular. It is such a great tool.  

I would like to ask about a procedure that seems not to be possible, but that may be useful to discuss.

The question is whether it is supported to insert some Angular component tag inside a Markdown file which is to be read afterwards. Ideally it would be something like this:

```
some-template.html
------------------

...
<markdown path="a-markdown-file.md"></markdown>
...
```
and then
```
a-markdown-file.md
------------------

...
<app-some-component></app-some-component>
...
```
In this direct way, it seems not to work (which is sensible, because this is not proper Markdown syntax). Would there be some roundabout when compiling? I have tried using the renderer to convert some protected character into the tags, but the result does not work.

In case it is useful, let me explain the context in which this question arises. I am building an application with lots of posts, so the combination Angular + Markdown is perfect: the posts are written in independent `.md` files, and Angular takes care of arranging everything. But the posts themselves usually have some repetitive chunks of code (to insert graphics, interactive content and others) and it would be great to replace this repetitive content with the aid of an Angular component.

Thank you very much for your attention; any suggestion or idea is welcome

**Comment by dimpu** [comment]
@jxm-math I'm sorry for the delay. I have tried different ways but this is not possible to implement right now. We are using `marked` library to convert markdown to HTML. It doesn't recognize custom element.  

I'm closing this issue for now. Feel free to open it again. If you find any solution.

**Comment by jxm-math** [comment]
@dimpu Thank you very much for your attention and efforts; it is sincerely very kind of you

**Comment by figuerres** [comment]
Actually i think you can do it 
i have a project for a Wiki  and in that i have links in markdown that need to be router links for navigation.
to make that work i call the markdown compile function and then pass that html to a directive that calls the angular compiler to convert the markup to where angular will use it.

see this [Question about dynamic elements](https://github.com/dimpu/angular2-markdown/issues/80)
for some info and a link to a plunker that has the directive code.
