### ISSUE TITLE
Upgrade to Angular 5?

### ISSUE THREAD

**Issue by rtm** [dimpu/angular2-markdown#97]
Are there any plans to bump the angular dependencies in package.json to include v5?

**Comment by dimpu** [comment]
I'm on it actually.

**Comment by NikoRoberts** [comment]
Is there an ETA for this? Have you started work on it @dimpu ?

**Comment by dimpu** [comment]
@NikoRoberts Ya I'm working on it. Maybe by week after next week.

**Comment by dimpu** [comment]
Hi Guys. Now it supports ng 5 too.

**Comment by NikoRoberts** [comment]
great, thank you 👏
