### ISSUE TITLE
Angualr still renders code and adds debug properties

### ISSUE THREAD

**Issue by vapits** [dimpu/angular2-markdown#98]
Hi there,

I'm experiencing this very strange behavior. Angular seems to render the code and then in my page I see also the shadow debug attributes in html elements.
Here's my code:
```
<div Markdown>
    ```
    <h1>Heading 1</h1>
    <h2>Heading 3</h2>
    <h3>Heading 3</h3>
    <h4>Heading 4</h4>
    <h5>Heading 5</h5>
    ```
</div>
```

And here's what I get:
![image](https://user-images.githubusercontent.com/8594758/32601303-7356cec6-c542-11e7-8cc0-612bf4605a0c.png)

Any ideas?

I'm using latest Angular 5 and Latest CLI.

Also if I use the `data` input then it doesn't gives the same issue though it adds space infornt of the first line of the code:
![image](https://user-images.githubusercontent.com/8594758/32601629-916683d8-c543-11e7-8fd9-e6d61d78f181.png)

**Comment by dimpu** [comment]
@vapits I'm not sure how you are doing this. Could you submit a plunker.
